spring:
  application:
    name: gateway
server:
  port: 9092

  servlet:
    context-path: /gateway
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defautZone: http://localhost:9091/eureka/
    fetch-registry: true
    register-with-eureka: true

    
#zuul:
#  routes:
#    course:
#      service-id: course
#      path: /course/**     
#  sensitive-headers: Cookie   
    
      