server:
  port: ${PORT:0}

  
spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/devdojo?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: devdojo
      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
   service-url:
      defautZone: http://localhost:9091/eureka
   fetch-registry: true
   register-with-eureka: true
