server:
  port: 9092

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defautZone: http://localhost:9091/eureka/
    fetch-registry: true
    register-with-eureka: true
  
spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/devdojo?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: devdojo
      
